### PR TITLE
Added X-Requested-With header to request object

### PR DESCRIPTION
**Pull request by pistom**
This is very useful to detect on server side ajax/no-ajax request.

### CODE REVIEW

**Comment by cferdinandi** [comment]
Hi, just took this repository over from Todd. Could you give me a little more information about what this does and why I would want to add it?

**Comment by pistom** [comment]
Hi, 
By receiving this request header, we can guess that the request is xhttprequest or standard and we can prepare a specific response.
https://davidwalsh.name/detect-ajax

**Comment by cferdinandi** [comment]
Will be addressed by https://github.com/cferdinandi/atomic/pull/40

**Comment by garygreen** [comment]
Would be nice if this was the default option. Although #40 allows you to set multiple headers, all modern ajax based libraries send `X-Requested-With` which is often used on the server side to determine what response to give.

**Comment by cferdinandi** [comment]
Does this seem reasonable as the default?

```js
headers: {
    'X-Requested-With': 'XMLHttpRequest'
}
```

**Comment by garygreen** [comment]
Done a bit of digging around. Maybe it wouldn't make sense to have it as the default because it can interfere with cross domain requests.

jQuery automatically adds the `X-Requested-With` header as long as it's not cross domain.
Axios doesn't
However, both do automatically add an accepted content type of `'Accept': 'application/json, text/plain, */*'` (obviously in order of preference; prefer json response, if not plain text)

If this isn't made the default, I do think we need to at least consider #68 because it would be a real pain the bum to have to add a wrapper around Atomic just to be able to hint to your server what data type your expecting. For most people, a sensible default is json and if the server doesn't want to respond to json, then plain.

**Comment by garygreen** [comment]
Sypmhony uses it to help determine what response and/or along with accept content types: https://github.com/symfony/symfony/blob/510977dd193b21a18b86855cba9f9dfef2d9d0bb/src/Symfony/Component/HttpFoundation/Request.php#L1690

Laravel provides similar functionality, various ways of checking:
[ajax](https://github.com/laravel/framework/blob/5312a2de904e7a47543fda8a3ac66f8b74ee86d2/src/Illuminate/Http/Request.php#L227) - checks for existence of X-Requested-With: XMLHttpRequest
[wantsJson](https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/src/Illuminate/Http/Concerns/InteractsWithContentTypes.php#L48) - checks for 'json' inside `Accept` header
[expectsJson](https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/src/Illuminate/Http/Concerns/InteractsWithContentTypes.php#L38) - checks for either `XMLHttpRequest` or accept header, basically guesses if response wants json.

This is why I think it's so important having the ability to set default values because it would be highly frustrating having to stub those out to another variable and merge those in every time, or add a wrapper around Atomic. It would be so much easier to just set whatever defaults you want.

**Comment by cferdinandi** [comment]
Are those values not configurable with atomic today? I'm assuming those are headers?

**Pull request closed without merging**
