### PR TITLE
Fix and update unit tests, npm test to run.

### PR DESCRIPTION
**Pull request by garygreen**
image

😄

### CODE REVIEW

**Comment by cferdinandi** [comment]
Hey, thanks so much for this! Any reason you ditched Gulp/Karma for NPM on these? Also, the move from PhantomJS to Chrome Headless... can you say more? PhantomJS has had some weird quirks in the past, so I'm curious about what Chrome does differently/better.

**Comment by garygreen** [comment]
Still using Karma but just using npm scripts to run the test runner. Gulp wasn't running any tests for me, nor was PhantomJS working but it could of just been my local machine, which leads me onto the next problem - you didn't have any dev dependencies for karma in your package json which meant you assumed any contributors would have those globally available (not always likely to be the case)

It's recommended to [always commit your package-lock](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/) file as well, even for libraries, as it leads to better contributor experience. It also helps / speeds up Travis CI.

I believe PhantomJS was created because headless Chrome wasn't really around at the time - it was the "go to" way of running tests in a simulated browser environment. But now we have headless Chrome and it's made PhantomJS pretty redundant, hence why the project is abandoned and the developer decided to stop supporting it.

**Comment by cferdinandi** [comment]
You've made it pretty clear that you have preferences that are different from mine. That's totally cool, but please stop assuming that the way you like to do things is inherently better than the way I or other people like to do things. 

 I maintain several dozen open source projects, and use the same configurable God file with all of them for years and consistent and predictable behavior. 

 Since you seem so dissatisfied with so many of my choices, why don't you just for kids project and do whatever you want with it?

**Comment by garygreen** [comment]
Come on Chris, that was a totally unnecessary attack. I've spent time contributing to this project and made reasoned, well thought out points and suggestions. You seem to take everything to heart. As I said before, I'm grateful for everything you've done on the project and it's yours do as you wish, which is why I mentioned I would fork and do my own thing. I think that's definitely for the best now. Good luck with everything.

**Comment by cferdinandi** [comment]
I appreciate your contributions, but its obvious to me that you want something that's more like Axios or jQuery (since you've mentioned "how they do things" at various points). 

I think you'd be happier with one of those. Not a personal attack, just an observation.

**Pull request closed without merging**
